-- English 5-letter answer list for Wordle
-- 2307 words
--
-- Two lists, as Wordle itself does it: this one holds words common enough to
-- be a fair answer, guesses_en.lua holds everything else the game will still
-- accept as a guess. Before this split there was one 716-word list doing both
-- jobs, so ordinary English guesses were rejected as "not a word".
--
-- Built from the intersection of ENABLE (Public Domain, see guesses_en.lua)
-- and SCOWL size 35 -- Copyright 2000-2018 Kevin Atkinson, used under SCOWL's
-- permission to use, copy, modify, distribute and sell these word lists and
-- the output created from them, provided this notice is kept. Obtained from
-- https://app.aspell.net/create. Plurals and third-person verb forms are
-- dropped (they make cheap answers), as are words unsuitable as a puzzle
-- answer; all of them remain valid guesses. The previously shipped list is
-- folded in unchanged.
local words = {}
local raw = [[
ABACK,ABATE,ABBEY,ABBOT,ABHOR,ABIDE,ABLER,ABODE,ABORT,ABOUT,ABOVE,ABUSE,ABYSS,ACHED,ACING,ACORN,ACRID,ACTED,ACTOR,ACUTE,ADAGE,ADAPT,ADDED,ADEPT,ADMIT,
ADOBE,ADOPT,ADORE,ADORN,ADULT,AFFIX,AFOOT,AFTER,AGAIN,AGENT,AGILE,AGING,AGLOW,AGONY,AGREE,AHEAD,AIDED,AILED,AIMED,AIRED,AISLE,ALARM,ALBUM,ALERT,ALGAE,
ALIAS,ALIBI,ALIEN,ALIGN,ALIKE,ALIVE,ALLAY,ALLEY,ALLOT,ALLOW,ALLOY,ALOFT,ALONE,ALONG,ALOOF,ALOUD,ALPHA,ALTAR,ALTER,AMASS,AMAZE,AMBER,AMBLE,AMEND,AMISS,
AMONG,AMPLE,AMPLY,AMUSE,ANGEL,ANGER,ANGLE,ANGRY,ANGST,ANIME,ANKLE,ANNEX,ANNOY,ANNUL,ANVIL,AORTA,APART,APING,APPLE,APPLY,APRON,APTER,APTLY,ARBOR,ARCED,
ARDOR,ARENA,ARGUE,ARISE,ARMED,ARMOR,AROMA,AROSE,ARRAY,ARROW,ARSON,ASHEN,ASHES,ASIDE,ASKED,ASKEW,ASPEN,ASSES,ASSET,ATLAS,ATONE,ATTIC,AUDIO,AUDIT,AURAL,
AVAIL,AVERT,AVOID,AWAIT,AWAKE,AWARD,AWARE,AWFUL,AWING,AWOKE,AXING,AXIOM,AZURE,BACON,BADGE,BADLY,BAGEL,BAGGY,BAKED,BAKER,BALED,BALMY,BANAL,BANDY,BANJO,
BARED,BARER,BARGE,BARON,BASED,BASER,BASES,BASIC,BASIL,BASIN,BASIS,BASTE,BATCH,BATHE,BATON,BAWDY,BAYED,BAYOU,BEACH,BEADY,BEARD,BEAST,BEECH,BEEFY,BEFIT,
BEGAN,BEGIN,BEGUN,BEIGE,BEING,BELCH,BELIE,BELLY,BELOW,BENCH,BERET,BERRY,BERTH,BESET,BIBLE,BIGOT,BIKED,BINGO,BIPED,BIRCH,BIRTH,BISON,BLACK,BLADE,BLAME,
BLAND,BLANK,BLARE,BLASE,BLAST,BLAZE,BLEAK,BLEAT,BLEED,BLEND,BLESS,BLIMP,BLIND,BLINK,BLISS,BLITZ,BLOCK,BLOND,BLOOD,BLOOM,BLOWN,BLUED,BLUER,BLUFF,BLUNT,
BLURB,BLURT,BLUSH,BOARD,BOAST,BODED,BOGUS,BONED,BONUS,BOOED,BOOST,BOOTH,BOOTY,BOOZE,BORED,BORNE,BOSSY,BOTCH,BOUGH,BOUND,BOWED,BOWEL,BOXED,BOXER,BOXES,
BRACE,BRAID,BRAIN,BRAKE,BRAND,BRASH,BRASS,BRAVE,BRAVO,BRAWL,BRAWN,BREAD,BREAK,BREED,BRIBE,BRICK,BRIDE,BRIEF,BRINE,BRING,BRINK,BRINY,BRISK,BROAD,BROIL,
BROKE,BROOD,BROOK,BROOM,BROTH,BROWN,BRUNT,BRUSH,BRUTE,BUDDY,BUDGE,BUGGY,BUGLE,BUILD,BUILT,BULGE,BULKY,BULLY,BUMPY,BUNCH,BUNNY,BURLY,BURNT,BURRO,BURST,
BUSED,BUSES,BUSHY,BUTTE,BUXOM,BUYER,BYWAY,CABIN,CABLE,CACAO,CACHE,CACTI,CADET,CAGED,CAGEY,CAKED,CAMEL,CAMEO,CANAL,CANDY,CANED,CANNY,CANOE,CANON,CAPED,
CAPER,CARAT,CARED,CARGO,CAROL,CARRY,CARVE,CASED,CASTE,CATCH,CATER,CAULK,CAUSE,CAVED,CAWED,CEASE,CEDAR,CEDED,CELLO,CHAFE,CHAFF,CHAIN,CHAIR,CHALK,CHAMP,
CHANT,CHARM,CHART,CHASE,CHASM,CHEAP,CHEAT,CHECK,CHEEK,CHEEP,CHEER,CHESS,CHEST,CHEWY,CHICK,CHIDE,CHIEF,CHILD,CHILI,CHILL,CHIME,CHIMP,CHINA,CHINK,CHIPS,
CHIRP,CHOIR,CHOKE,CHORD,CHORE,CHOSE,CHUCK,CHUNK,CHURN,CHUTE,CIDER,CIGAR,CINCH,CIRCA,CITED,CIVIC,CIVIL,CLACK,CLAIM,CLAMP,CLANG,CLANK,CLASH,CLASP,CLASS,
CLEAN,CLEAR,CLEAT,CLEFT,CLERK,CLICK,CLIFF,CLIMB,CLING,CLINK,CLOAK,CLOCK,CLONE,CLOSE,CLOTH,CLOUD,CLOUT,CLOVE,CLOWN,CLUCK,CLUED,CLUMP,CLUNG,COACH,COAST,
COBRA,COCKY,COCOA,CODED,COKED,COLIC,COLON,COLOR,COMET,COMIC,COMMA,COOED,COPED,CORAL,CORED,CORNY,CORPS,COUCH,COUGH,COULD,COUNT,COURT,COVER,COVET,COWED,
COWER,COYER,CRACK,CRAFT,CRAMP,CRANE,CRANK,CRASH,CRASS,CRATE,CRAVE,CRAWL,CRAZE,CRAZY,CREAK,CREAM,CREED,CREEK,CREEP,CREPE,CREPT,CREST,CRIED,CRIES,CRIME,
CRISP,CROAK,CROCK,CRONY,CROOK,CROON,CROSS,CROWD,CROWN,CRUDE,CRUEL,CRUMB,CRUSH,CRUST,CRYPT,CUBED,CUBIC,CUING,CURED,CURIO,CURLY,CURRY,CURSE,CURVE,CUTER,
CYCLE,CYNIC,DADDY,DAILY,DAIRY,DAISY,DALLY,DANCE,DANDY,DARED,DARTS,DATED,DATUM,DAUNT,DAZED,DEALT,DEATH,DEBIT,DEBUG,DEBUT,DECAY,DECOY,DECRY,DEFER,DEIFY,
DEIGN,DEITY,DELAY,DELTA,DELVE,DEMON,DENIM,DENSE,DEPOT,DEPTH,DERBY,DETER,DEVIL,DIARY,DICED,DIGIT,DIKED,DIMLY,DINED,DINER,DINGY,DIRER,DIRGE,DIRTY,DISCO,
DITCH,DITTO,DITTY,DIVED,DIVER,DIZZY,DODGE,DOGMA,DOILY,DOING,DOLED,DOLLY,DOMED,DONOR,DONUT,DOPED,DOPEY,DOSED,DOTED,DOUBT,DOUGH,DOUSE,DOWDY,DOWNY,DOWRY,
DOZED,DOZEN,DRAFT,DRAIN,DRAMA,DRANK,DRAPE,DRAWL,DRAWN,DREAD,DREAM,DRESS,DRIED,DRIER,DRIES,DRIFT,DRILL,DRINK,DRIVE,DROLL,DRONE,DROOL,DROOP,DROSS,DROVE,
DROWN,DRUNK,DRYER,DRYLY,DUDED,DULLY,DUMMY,DUMPY,DUNCE,DUPED,DUSKY,DUSTY,DUVET,DWARF,DWELL,DWELT,DYING,EAGER,EAGLE,EARLY,EARTH,EASED,EASEL,EATEN,EATER,
EBBED,EBONY,EDGED,EDICT,EERIE,EGGED,EIGHT,EJECT,EKING,ELBOW,ELDER,ELECT,ELEGY,ELITE,ELOPE,ELUDE,ELVES,EMAIL,EMBED,EMBER,EMPTY,ENACT,ENDED,ENDOW,ENEMA,
ENEMY,ENJOY,ENSUE,ENTER,ENTRY,ENVOY,EPOCH,EQUAL,EQUIP,ERASE,ERECT,ERODE,ERRED,ERROR,ERUPT,ESSAY,ETHER,ETHIC,ETHOS,EVADE,EVENT,EVERY,EVICT,EVOKE,EXACT,
EXALT,EXCEL,EXERT,EXILE,EXIST,EXPEL,EXTOL,EXTRA,EXUDE,EXULT,FABLE,FACED,FACET,FADED,FAGOT,FAINT,FAIRY,FAITH,FAKED,FALSE,FAMED,FANCY,FARCE,FARED,FATAL,
FATED,FATTY,FAULT,FAUNA,FAVOR,FAZED,FEAST,FECES,FEIGN,FEINT,FELON,FENCE,FERAL,FERRY,FETAL,FETCH,FETED,FETID,FETUS,FEVER,FEWER,FIBER,FICHE,FIELD,FIEND,
FIERY,FIFTH,FIFTY,FIGHT,FILCH,FILED,FILLY,FILMY,FILTH,FINAL,FINCH,FINED,FINER,FIRED,FIRST,FISHY,FIVER,FIXED,FIXES,FIZZY,FLAIL,FLAIR,FLAKE,FLAKY,FLAME,
FLANK,FLARE,FLASH,FLASK,FLECK,FLEET,FLESH,FLICK,FLIED,FLIER,FLIES,FLING,FLINT,FLIRT,FLOAT,FLOCK,FLOOD,FLOOR,FLORA,FLOSS,FLOUR,FLOUT,FLOWN,FLUFF,FLUID,
FLUKE,FLUNG,FLUNK,FLUSH,FLUTE,FOAMY,FOCAL,FOCUS,FOGGY,FOIST,FOLLY,FORAY,FORCE,FORGE,FORGO,FORTE,FORTH,FORTY,FORUM,FOUND,FOUNT,FOXED,FOXES,FOYER,FRAIL,
FRAME,FRANC,FRANK,FRAUD,FREAK,FREED,FREER,FRESH,FRIAR,FRIED,FRIES,FRILL,FRISK,FROCK,FROND,FRONT,FROST,FROTH,FROWN,FROZE,FRUIT,FUDGE,FULLY,FUMED,FUNGI,
FUNKY,FUNNY,FUROR,FURRY,FUSED,FUSSY,FUZZY,GABLE,GAILY,GAINS,GAMED,GAMER,GAMMA,GAMUT,GAPED,GASES,GATED,GAUDY,GAUGE,GAUNT,GAUZE,GAVEL,GAWKY,GAYER,GAZED,
GEESE,GENIE,GENII,GENRE,GHOST,GHOUL,GIANT,GIBED,GIDDY,GIMME,GIRTH,GIVEN,GLADE,GLAND,GLARE,GLASS,GLAZE,GLEAM,GLEAN,GLIDE,GLINT,GLOAT,GLOBE,GLOOM,GLORY,
GLOSS,GLOVE,GLUED,GNASH,GNOME,GODLY,GOING,GONER,GOODY,GOOEY,GOOFY,GOOSE,GORED,GORGE,GOUGE,GOURD,GRACE,GRADE,GRAFT,GRAIN,GRAND,GRANT,GRAPE,GRAPH,GRASP,
GRASS,GRATE,GRAVE,GRAVY,GRAZE,GREAT,GREED,GREEN,GREET,GRIEF,GRILL,GRIME,GRIMY,GRIND,GRIPE,GROAN,GROIN,GROOM,GROPE,GROSS,GROUP,GROVE,GROWL,GROWN,GRUEL,
GRUFF,GRUNT,GUARD,GUESS,GUEST,GUIDE,GUILD,GUILE,GUILT,GUISE,GULCH,GULLY,GUMMY,GUPPY,GUSTO,GUSTY,GUYED,HABIT,HAIKU,HAIRY,HALED,HALER,HALVE,HANDS,HANDY,
HAPPY,HARDY,HARED,HAREM,HARRY,HARSH,HASTE,HASTY,HATCH,HATED,HAUNT,HAVEN,HAVOC,HAYED,HAZED,HAZEL,HEADY,HEARD,HEART,HEATH,HEAVE,HEAVY,HEDGE,HEFTY,HELLO,
HENCE,HERON,HERTZ,HEWED,HIDED,HIKED,HIKER,HILLY,HINGE,HIRED,HITCH,HIVED,HOARD,HOBBY,HOIST,HOLED,HOLLY,HOMED,HOMEY,HONED,HONEY,HONOR,HOPED,HORDE,HORSE,
HOSED,HOTEL,HOTLY,HOUND,HOUSE,HOVEL,HOVER,HUFFY,HUGER,HUMAN,HUMID,HUMOR,HUNCH,HURRY,HUSKY,HUTCH,HYENA,ICIER,ICING,IDEAL,IDIOM,IDIOT,IDLED,IDLER,IGLOO,
IMAGE,IMPEL,IMPLY,INANE,INCUR,INDEX,INEPT,INERT,INFER,INFIX,INKED,INLAY,INLET,INNER,INPUT,INTER,INTRO,IRATE,IRKED,IRONY,ISSUE,ITCHY,IVIES,IVORY,JADED,
JAPAN,JAUNT,JAWED,JELLY,JERKY,JETTY,JEWEL,JIBED,JIFFY,JOINT,JOKED,JOKER,JOLLY,JOYED,JUDGE,JUICE,JUICY,JUMBO,JUMPY,JUNTA,JUROR,KARAT,KARMA,KAYAK,KEYED,
KHAKI,KINKY,KIOSK,KITED,KITTY,KNACK,KNEAD,KNEED,KNEEL,KNELT,KNIFE,KNOCK,KNOLL,KNOWN,KOALA,LABEL,LABOR,LACED,LADEN,LADLE,LAGER,LAMED,LAMER,LANCE,LANKY,
LAPEL,LAPSE,LARGE,LARVA,LASER,LATCH,LATER,LATEX,LATHE,LAUGH,LAXER,LAYER,LEACH,LEAFY,LEAKY,LEAPT,LEARN,LEASE,LEASH,LEAST,LEAVE,LEDGE,LEECH,LEERY,LEGAL,
LEMON,LEPER,LETUP,LEVEE,LEVEL,LEVER,LIBEL,LIGHT,LIKED,LIKEN,LILAC,LIMBO,LIMED,LIMIT,LINED,LINEN,LINER,LINGO,LITER,LITHE,LIVED,LIVEN,LIVER,LIVID,LLAMA,
LOATH,LOBBY,LOCAL,LODGE,LOFTY,LOGIC,LOONY,LOOSE,LOPED,LORRY,LOSER,LOTUS,LOUSE,LOUSY,LOVED,LOVER,LOWED,LOWER,LOWLY,LOYAL,LUCID,LUCKY,LUMPY,LUNAR,LUNCH,
LUNGE,LURCH,LURED,LURID,LUSTY,LYING,LYMPH,LYNCH,LYRIC,MACED,MACHO,MADAM,MADLY,MAGIC,MAIZE,MAJOR,MAKER,MANGE,MANGO,MANGY,MANIA,MANIC,MANLY,MANOR,MAPLE,
MARCH,MARIA,MARRY,MARSH,MASON,MATCH,MATED,MATTE,MAUVE,MAXIM,MAYBE,MAYOR,MEALY,MEANT,MEDAL,MEDIA,MELON,MERCY,MERGE,MERIT,MERRY,MESSY,METAL,METED,METER,
MEWED,MIDST,MIGHT,MIKED,MILKY,MIMED,MIMIC,MINCE,MINED,MINER,MINOR,MINUS,MIRED,MIRTH,MISER,MISTY,MIXED,MIXER,MIXES,MODAL,MODEL,MOIST,MOLAR,MOLDY,MONEY,
MONTH,MOODY,MOOED,MOOSE,MOPED,MORAL,MORON,MOSSY,MOTEL,MOTIF,MOTOR,MOTTO,MOUND,MOUNT,MOURN,MOUSE,MOUSY,MOUTH,MOVED,MOVER,MOVIE,MOWED,MOWER,MUCUS,MUDDY,
MUGGY,MULCH,MUMMY,MUNCH,MURAL,MURKY,MUSED,MUSHY,MUSIC,MUSTY,MUTED,MUTER,NAIVE,NAKED,NAMED,NASAL,NASTY,NATTY,NAVAL,NAVEL,NEEDY,NEIGH,NERVE,NEVER,NEWER,
NEWLY,NEWSY,NICER,NICHE,NIECE,NIFTY,NIGHT,NINNY,NINTH,NIPPY,NOBLE,NOBLY,NOISE,NOISY,NOMAD,NOOSE,NORTH,NOSED,NOTCH,NOTED,NOVEL,NUDER,NUDGE,NURSE,NUTTY,
NYLON,NYMPH,OARED,OASES,OASIS,OBESE,OCCUR,OCEAN,OCTAL,ODDER,ODDLY,OFFED,OFFER,OFTEN,OGLED,OILED,OLDEN,OLDER,OLIVE,OMEGA,ONION,ONSET,OOZED,OPERA,OPIUM,
OPTED,OPTIC,ORBIT,ORDER,ORGAN,OTHER,OTTER,OUGHT,OUNCE,OUTDO,OUTED,OUTER,OVARY,OVERT,OWING,OWNED,OWNER,OXIDE,OZONE,PACED,PADDY,PAGAN,PAGED,PAGER,PAINT,
PALED,PALER,PANDA,PANEL,PANIC,PANSY,PAPAL,PAPER,PARCH,PARED,PARKA,PARSE,PARTY,PASSE,PASTA,PASTE,PASTY,PATCH,PATIO,PATTY,PAUSE,PAVED,PAWED,PAYED,PEACE,
PEACH,PEARL,PECAN,PEDAL,PEEVE,PENAL,PENCE,PENNY,PEONY,PERCH,PERIL,PERKY,PESKY,PETAL,PETER,PETTY,PHASE,PHONE,PHONY,PHOTO,PIANO,PICKY,PIECE,PIETY,PIKED,
PILED,PILOT,PINCH,PINED,PIOUS,PIPED,PIQUE,PITCH,PITHY,PIVOT,PIXEL,PIXIE,PIZZA,PLACE,PLAID,PLAIN,PLANE,PLANK,PLANT,PLATE,PLAZA,PLEAD,PLEAT,PLIED,PLUCK,
PLUME,PLUMP,PLUSH,POACH,POINT,POISE,POKED,POKER,POLAR,POLED,POLIO,POLKA,POLYP,POPPY,PORCH,PORED,POSED,POUCH,POUND,POWER,PRANK,PRAWN,PREEN,PRESS,PRICE,
PRIDE,PRIED,PRIES,PRIME,PRIMP,PRINT,PRIOR,PRISM,PRIVY,PRIZE,PROBE,PRONE,PRONG,PROOF,PROSE,PROUD,PROVE,PROWL,PROXY,PRUDE,PRUNE,PSALM,PUDGY,PUFFY,PUKED,
PULSE,PUNCH,PUPIL,PUPPY,PUREE,PURER,PURGE,PURSE,PUSHY,PUTTY,QUACK,QUAIL,QUAKE,QUALM,QUARK,QUART,QUASH,QUEEN,QUELL,QUERY,QUEST,QUEUE,QUICK,QUIET,QUILL,
QUILT,QUIRK,QUITE,QUOTA,QUOTE,RABBI,RABID,RACED,RACER,RADAR,RADII,RADIO,RAGED,RAINY,RAISE,RAKED,RALLY,RANCH,RANGE,RAPID,RARED,RARER,RATED,RATIO,RATTY,
RAVED,RAVEL,RAVEN,RAWER,RAYON,RAZED,RAZOR,REACH,REACT,READY,REALM,REBEL,REBUT,RECAP,RECUR,REDID,REFER,REGAL,REIGN,RELAX,RELAY,RELIC,REMIT,REMIX,RENAL,
RENEW,REPAY,REPEL,REPLY,RESET,RESIN,RETCH,RETRO,RETRY,REUSE,REVEL,REVUE,RHINO,RHYME,RICED,RIDER,RIDGE,RIFER,RIFLE,RIGHT,RIGID,RIGOR,RILED,RINSE,RIPEN,
RIPER,RISEN,RISER,RISKY,RIVAL,RIVER,RIVET,ROACH,ROAST,ROBED,ROBIN,ROBOT,ROCKY,RODEO,ROGUE,ROMAN,ROOMY,ROOST,ROPED,ROTOR,ROUGE,ROUGH,ROUND,ROUSE,ROUTE,
ROWDY,ROWED,ROYAL,RUDDY,RUDER,RUGBY,RUING,RULED,RULER,RUMMY,RUMOR,RUNNY,RURAL,RUSTY,SABER,SADLY,SAFER,SAGER,SAINT,SALAD,SALLY,SALON,SALTY,SALVE,SANDY,
SANER,SASSY,SATIN,SAUCE,SAUCY,SAUNA,SAUTE,SAVED,SAVER,SAVOR,SAVVY,SAWED,SCALD,SCALE,SCALP,SCALY,SCANT,SCARE,SCARF,SCARY,SCENE,SCENT,SCOFF,SCOLD,SCOOP,
SCOOT,SCOPE,SCORE,SCORN,SCOUR,SCOUT,SCOWL,SCRAM,SCRAP,SCREW,SCRUB,SCUFF,SEDAN,SEEDY,SEIZE,SENSE,SERUM,SERVE,SETUP,SEVEN,SEVER,SEWED,SEWER,SEXED,SEXES,
SHACK,SHADE,SHADY,SHAFT,SHAKE,SHAKY,SHALL,SHALT,SHAME,SHAPE,SHARE,SHARK,SHARP,SHAVE,SHAWL,SHEAF,SHEAR,SHEEN,SHEEP,SHEER,SHEET,SHELF,SHELL,SHIED,SHIES,
SHIFT,SHINE,SHINY,SHIRE,SHIRK,SHIRT,SHOAL,SHOCK,SHONE,SHOOK,SHOOT,SHORE,SHORN,SHORT,SHOUT,SHOVE,SHOWN,SHOWY,SHRED,SHREW,SHRUB,SHRUG,SHUCK,SHUNT,SHYER,
SIDED,SIDLE,SIEGE,SIEVE,SIGHT,SIGMA,SILLY,SINCE,SINEW,SINGE,SINUS,SIRED,SIREN,SITED,SIXES,SIXTH,SIXTY,SIZED,SKATE,SKEIN,SKIED,SKIES,SKILL,SKIMP,SKIRT,
SKULK,SKULL,SKUNK,SLACK,SLAIN,SLAKE,SLANG,SLANT,SLASH,SLATE,SLAVE,SLEEK,SLEEP,SLEET,SLEPT,SLICE,SLICK,SLIDE,SLIER,SLIME,SLIMY,SLING,SLINK,SLOPE,SLOSH,
SLOTH,SLUMP,SLUNG,SLUNK,SLUSH,SLYLY,SMACK,SMALL,SMART,SMASH,SMEAR,SMELL,SMELT,SMILE,SMIRK,SMITH,SMOCK,SMOKE,SMOKY,SNACK,SNAIL,SNAKE,SNARE,SNARL,SNEAK,
SNEER,SNIDE,SNIFF,SNIPE,SNOOP,SNORE,SNORT,SNOUT,SNOWY,SNUFF,SOAPY,SOBER,SOGGY,SOLAR,SOLED,SOLID,SOLVE,SONIC,SOOTY,SORER,SORRY,SOUND,SOUTH,SOWED,SPACE,
SPADE,SPANK,SPARE,SPARK,SPASM,SPATE,SPAWN,SPEAK,SPEAR,SPECK,SPEED,SPELL,SPEND,SPENT,SPICE,SPICY,SPIED,SPIES,SPIKE,SPILL,SPINE,SPIRE,SPITE,SPLAT,SPLIT,
SPOIL,SPOKE,SPOOF,SPOOK,SPOOL,SPOON,SPORT,SPOUT,SPRAY,SPREE,SPRIG,SPUNK,SPURN,SPURT,SQUAD,SQUAT,SQUID,STACK,STAFF,STAGE,STAID,STAIN,STAIR,STAKE,STALE,
STALK,STALL,STAMP,STAND,STANK,STARE,STARK,START,STATE,STAVE,STEAK,STEAL,STEAM,STEEL,STEEP,STEER,STERN,STICK,STIFF,STILL,STING,STINK,STINT,STOCK,STOKE,
STOLE,STOMP,STONE,STONY,STOOD,STOOL,STOOP,STORE,STORK,STORM,STORY,STOUT,STOVE,STRAP,STRAW,STRAY,STREW,STRIP,STRUM,STRUT,STUCK,STUDY,STUFF,STUMP,STUNG,
STUNK,STUNT,STYLE,SUAVE,SUEDE,SUGAR,SUING,SUITE,SULKY,SUNNY,SUNUP,SUPER,SURER,SURGE,SURLY,SWAMP,SWARM,SWEAR,SWEAT,SWEEP,SWEET,SWELL,SWEPT,SWIFT,SWILL,
SWINE,SWING,SWIPE,SWIRL,SWISH,SWOON,SWOOP,SWORD,SWORE,SWORN,SWUNG,SYRUP,TABBY,TABLE,TABOO,TACIT,TACKY,TAINT,TAKEN,TALLY,TALON,TAMED,TAMER,TANGO,TAPED,
TAPER,TARDY,TARRY,TASTE,TASTY,TATTY,TAUNT,TAWNY,TAXED,TAXES,TEACH,TEASE,TEETH,TEMPO,TEMPT,TENET,TENOR,TENSE,TENTH,TEPEE,TEPID,TERMS,TERSE,THANK,THEFT,
THEIR,THEME,THERE,THESE,THETA,THICK,THIEF,THIGH,THING,THINK,THIRD,THONG,THORN,THOSE,THREE,THREW,THROB,THROW,THUMB,THUMP,THYME,TIARA,TIDAL,TIDED,TIGER,
TIGHT,TILDE,TILED,TIMED,TIMER,TIMID,TINGE,TINNY,TIPSY,TIRED,TITLE,TOAST,TODAY,TOKEN,TONAL,TONED,TONIC,TOOTH,TOPAZ,TOPIC,TORCH,TORSO,TOTAL,TOTED,TOTEM,
TOUCH,TOUGH,TOWED,TOWEL,TOWER,TOXIC,TOXIN,TOYED,TRACE,TRACK,TRACT,TRADE,TRAIL,TRAIN,TRAIT,TRAMP,TRASH,TRAWL,TREAD,TREAT,TREED,TREND,TRIAL,TRIBE,TRICK,
TRIED,TRIES,TRILL,TRIPE,TRITE,TROLL,TROOP,TROUT,TRUCE,TRUCK,TRUED,TRUER,TRULY,TRUMP,TRUNK,TRUST,TRUTH,TUBED,TULIP,TUMMY,TUMOR,TUNED,TUNER,TUNIC,TUTOR,
TWANG,TWEAK,TWEED,TWEET,TWICE,TWINE,TWIRL,TWIST,TYING,TYPED,UDDER,ULCER,ULTRA,UNCLE,UNCUT,UNDER,UNDID,UNDUE,UNFIT,UNIFY,UNION,UNITE,UNITY,UNSET,UNTIE,
UNTIL,UPEND,UPPED,UPPER,UPSET,URBAN,URGED,URINE,USAGE,USHER,USING,USUAL,USURP,UTERI,UTTER,VAGUE,VALET,VALID,VALOR,VALUE,VALVE,VAPOR,VAULT,VENOM,VENUE,
VERGE,VERSE,VERVE,VEXED,VEXES,VICAR,VICED,VIDEO,VIGIL,VIGOR,VILER,VILLA,VINYL,VIOLA,VIPER,VIRAL,VIRUS,VISED,VISIT,VISOR,VISTA,VITAL,VIVID,VOCAL,VODKA,
VOGUE,VOICE,VOMIT,VOTED,VOTER,VOUCH,VOWED,VOWEL,VYING,WADED,WAFER,WAGED,WAGER,WAGON,WAIST,WAIVE,WAKED,WAKEN,WALTZ,WANED,WASTE,WATCH,WATER,WAVED,WAVER,
WAXED,WAXES,WEARY,WEAVE,WEDGE,WEEDY,WEEST,WEIGH,WEIRD,WHACK,WHALE,WHARF,WHEAT,WHEEL,WHERE,WHICH,WHIFF,WHILE,WHINE,WHIRL,WHISK,WHITE,WHOLE,WHOOP,WHOSE,
WIDEN,WIDER,WIDOW,WIDTH,WIELD,WINCE,WINCH,WINDY,WINED,WIPED,WIPER,WIRED,WISER,WISPY,WITCH,WITTY,WOKEN,WOMAN,WOMEN,WOODY,WOOED,WORDY,WORLD,WORRY,WORSE,
WORST,WORTH,WOULD,WOUND,WOVEN,WOWED,WRATH,WREAK,WRECK,WREST,WRING,WRIST,WRITE,WRONG,WROTE,WRUNG,WRYER,YACHT,YEARN,YEAST,YESES,YIELD,YODEL,YOKED,YOKEL,
YOUNG,YOUTH,ZEBRA,ZESTY,ZONED,ZONES,ZOOMS
]]
for w in raw:gmatch("[A-Z]+") do
    words[#words + 1] = w
end
return words
